# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-19 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
